import { useCallback, useEffect, useRef, useState } from 'react'
import { ArrowRight, ArrowClockwise, Check, CaretRight, CircleNotch, ShieldCheck, ChatCircle, WarningCircle, Clock, X, UsersThree } from '@phosphor-icons/react'
import './demo-workspace.css'
import OfficeScene from './OfficeScene'
import ResolutionPanel, { type Resolution } from './ResolutionPanel'

type Event = { id:string; name:string; phase:string; at:string; level:string }
type Observation = { id:string; name:string; type:string; parent_observation_id:string|null; model:string; input:unknown; output:unknown; usage:Record<string,number> }
type Run = { run:{state:string}; task_graph:{tasks:{id:string; role:string; title:string; state:string; result:{summary:string}|null}[]}; model_usage:{actual_tokens:number|null; state:string}[] }
type Job = { selected_evidence_ids?:string[]; application_reference?:{content:string;source_commit:string;files?:{path:string;content?:string;truncated?:boolean}[]}; target_configuration?:{policy:string}; history?:{proposal:{version:number;summary:string};review:{decision:string;reason:string}}[]; id:string; incident_id?:string; capabilities?:{target_version_current?:boolean;investigation_allowed?:boolean}; message:string; state:string; error?:string; created_at:string; updated_at:string; reply:string|null; events:Event[]; observations:Observation[]; observation_state:string; findings:{key:string;summary:string}[]; triage?:{state:string;summary:string;reason?:string;auto_investigate?:boolean}; reused_lessons?:{id:string;title:string;source_incident_id:string;scope:string|Record<string,unknown>;summary:string}[]; elapsed_s?:number; analysis_state:string; analysis_error?:string; runs:Record<string,string>; investigations:Record<string,Run>; collaboration:null|{session_id:string;paused_members?:string[];events:{role:string;kind:string;summary:string;at:string;remote_message_id:string}[]}; run_history?:Partial<Record<'single'|'swarm',{run_id:string;policy_revision:number;token_limit:number;state:string;result_type?:string;known_total_tokens:number;usage_unknown_count:number;replaced_at?:string}[]>>; comparison?:Record<string,{state:string;elapsed_s:number;evidence_sha256:string;token_limit:number;model:string}>; proposal?:{sha256:string;summary:string;version:number;conclusion:string}; review?:{decision:string;reason:string}; resolution?:Resolution|null }
type Overview={application:string;environment:string;native:{configured:boolean;transport:string};tasks:Pick<Job,'id'|'message'|'state'>[]}
const labels:Record<string,string>={starting:'正在连接',running:'进行中',completed:'已完成',failed:'未完成',interrupted:'已中断',idle:'尚未开始',complete:'已完成',watching:'正在观察',waiting:'等待调用',connecting:'正在连接',verified:'上下文已同步',indexing:'正在同步上下文',unavailable:'观察数据暂不可用',succeeded:'已完成',claimed:'正在处理',open:'等待开始',blocked:'需要处理',investigator:'调查员',challenger_seed:'独立复核',challenger_review:'复核员',synthesizer:'协调员',coordinator:'协调员',reviewer:'复核员'}
const name=(s:string)=>labels[s]??s
const stepName=(s:string)=>({ChatOpenAI:'模型调用',LangGraph:'业务流程',RunnableCallable:'流程交接',route:'选择业务助手',order:'订单处理',refund:'退款处理','support-agent.chat':'本次业务任务',get_order_status:'查询订单状态',get_order_details:'读取订单详情',track_shipment:'查询物流',check_refund_eligibility:'检查退款资格',initiate_refund:'提交退款',get_payment_status:'查询付款状态',answer_faq:'查询业务政策'} as Record<string,string>)[s]??s
const display=(x:unknown)=>typeof x==='string'?x:JSON.stringify(x,null,2)
const triageLabel=(state?:string)=>({expected_boundary:'正常澄清 / 能力边界',human_requested:'请求人工协助',no_rule_finding:'未触发异常规则',manual_check_available:'可选人工核查',unexpected_handoff:'业务问题发生转交',unexpected_write:'发现意外写入',pipeline_error:'处理过程异常'} as Record<string,string>)[state??'']??'任务观察结果'
async function api<T>(path:string, body?:unknown, key?:string):Promise<T>{const response=await fetch('/api/v1/demo'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},body:body?JSON.stringify(body):undefined});const json=await response.json();if(!response.ok)throw new Error(json.error?.message??'请求失败，请重试');return json}
export default function DemoWorkspace(){
 const [overview,setOverview]=useState<Overview|null>(null),[selected,setSelected]=useState(()=>new URLSearchParams(location.search).get('task')??''),[job,setJob]=useState<Job|null>(null)
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState(''),[member,setMember]=useState('investigator'),[evidence,setEvidence]=useState<string[]>([]),[connectionError,setConnectionError]=useState(''),[autoInvestigate,setAutoInvestigate]=useState(true)
 const requestKey=useRef<string|null>(null), current=useRef(selected);current.current=selected
 const refresh=useCallback(async()=>{try{const state=await api<Overview>('/status');setOverview(state);const id=current.current;if(id){const next=await api<Job>('/tasks/'+id);if(current.current===id)setJob(next)}setConnectionError('')}catch{setConnectionError('连接暂时中断，正在重新连接。')}},[])
 useEffect(()=>{refresh();const timer=setInterval(refresh,1200);return()=>clearInterval(timer)},[refresh])
 useEffect(()=>{const back=()=>{const id=new URLSearchParams(location.search).get('task')??'';setSelected(id);current.current=id;setJob(null);setEvidence([]);refresh()};addEventListener('popstate',back);return()=>removeEventListener('popstate',back)},[refresh])
 function choose(id:string){setEvidence([]);setReason('');setError('');setSelected(id);setJob(null);const url=new URL(location.href);url.searchParams.set('task',id);history.pushState({},'',url);current.current=id;refresh()}
 async function act(action:()=>Promise<unknown>){setBusy(true);setError('');try{await action();await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function start(){if(!message.trim())return;requestKey.current??=crypto.randomUUID();await act(async()=>{const next=await api<Job>('/tasks',{message:message.trim(),auto_investigate:autoInvestigate},requestKey.current!);requestKey.current=null;choose(next.id);setMessage('')})}
 const working=overview?.tasks.some(t=>['starting','running'].includes(t.state))
 const picked=job?.selected_evidence_ids??evidence
 const reusedLessons=job?.reused_lessons??[]
 const resolutionReady=!!job?.incident_id&&job.analysis_state==='complete'&&job.observation_state==='verified'&&job.state==='completed'&&job.target_configuration?.policy==='legacy'
 const investigationAllowed=job?.capabilities?.investigation_allowed!==false
 const sourceCurrent=job?.capabilities?.target_version_current!==false
 const tasks=job?.investigations?.swarm?.task_graph.tasks??[]
 const collab=job?.collaboration?.events??[]
 const officeAgents=['observer','investigator','reviewer','coordinator'].map(role=>{const last=collab.filter(e=>e.role===role).at(-1);if(role==='observer')return {id:role,role,name:'观察员',status:job?.state==='running'?'working':'idle',heartbeat_at:job?.events.at(-1)?.at??null,task_id:job?.id??null,detail:job?.state==='running'?'正在读取业务执行事件，检查错误、耗时与转交人工。':'事件观察已结束，可继续核查业务依据。',capabilities:['application.observe']};return {id:role,role,name:name(role),status:job?.collaboration?.paused_members?.includes(role)?'blocked':last?.kind==='handoff'&&job?.analysis_state==='running'?'working':'idle',heartbeat_at:last?.at??null,task_id:job?.runs.swarm??null,detail:last?.summary??'等待任务',capabilities:[]}})
 useEffect(()=>{document.title='Section9 · Agent 治理工作台'},[])
 const officeEvents=collab.map((e,i)=>({event_id:e.remote_message_id,sequence:i,event_type:'message.sent',occurred_at:e.at,run_id:job?.runs.swarm??null,incident_id:null,producer:e.role,generation:job?.id??'',payload:{message:e.summary}}))
 return <div className="demo-app"><a href="#demo-main" className="demo-skip">跳至任务</a>
  <header className="demo-header"><a href="/demo" className="demo-brand"><span><ShieldCheck size={23} weight="fill"/></span>Section9</a><span className="demo-tag">Agent 治理工作台</span><button className="demo-icon" aria-label="刷新" onClick={refresh}><ArrowClockwise size={20}/></button></header>
  <div className="demo-layout"><aside className="demo-sidebar"><div className="demo-application"><span className="demo-avatar"><ChatCircle size={24}/></span><div><strong>客服助手</strong><small>本地演示业务数据</small></div></div><button className="demo-new" onClick={()=>{setSelected('');setJob(null);current.current='';history.pushState({},'', '/demo');setMessage('');setEvidence([]);setReason('');setError('')}}><span>新任务</span><ArrowRight size={18}/></button><h2>最近任务</h2><nav aria-label="历史任务">{overview?.tasks.map(t=><button key={t.id} className={selected===t.id?'is-selected':''} onClick={()=>choose(t.id)}><span>{t.message}</span><small>{name(t.state)}</small></button>)}{overview&&!overview.tasks.length&&<p className="demo-muted">你的任务会保存在这里。</p>}</nav><div className="demo-sidebar-foot"><ShieldCheck size={18}/><span>Section9 随任务观察<br/><small>发现疑点，或由你发起核查</small></span></div></aside>
  <main id="demo-main" className="demo-main"><div className="demo-title"><div><span className="demo-eyebrow">客服助手 · 订单与退款</span><h1>{job?'任务与观察':'交给助手，安心看它完成。'}</h1><p>{job?'业务执行、调用依据和治理进展，都在同一处。':'输入一个业务任务。Section9 会在旁观察，发现疑点时给出依据。'}</p></div><span className="demo-live"><i/>{working?'任务执行中':'等待新任务'}</span></div>
   {(error||connectionError)&&<div className="demo-error" role="alert"><WarningCircle size={20}/><span>{error||connectionError}</span><button onClick={refresh}>重新连接</button></div>}
   <section className="demo-composer" aria-label="提交业务任务"><label htmlFor="business-question">你希望客服助手做什么？</label><textarea id="business-question" value={message} onChange={e=>{setMessage(e.target.value);requestKey.current=null}} placeholder="例如：查询订单 1001 的状态，并说明查询依据。" maxLength={4000}/><div className="demo-composer-options"><small>可查询订单、物流、退款资格及常见问题。</small><label className="s9-auto-investigate"><input type="checkbox" checked={autoInvestigate} onChange={e=>setAutoInvestigate(e.target.checked)}/>发现疑点时自动协作核查</label><button className="demo-primary" disabled={busy||working||!message.trim()} onClick={start}>{busy?<CircleNotch className="spinning"/>:<ArrowRight/>}开始任务</button></div></section>
   {!selected&&<section className="demo-welcome"><div><span>01</span><h2>助手完成任务</h2><p>实际调用模型和业务工具，处理你提出的问题。</p></div><div><span>02</span><h2>Section9 在旁观察</h2><p>跟踪执行过程，把需要核实的步骤标出来。</p></div><div><span>03</span><h2>查看依据，再做决定</h2><p>展开协作与证据，审核有依据的处理建议。</p></div></section>}
   {selected&&!job&&<p role="status">正在读取任务…</p>}
   {job&&<div className="demo-columns"><div className="demo-task-column"><section className="demo-panel"><div className="demo-section-title"><h2>业务任务</h2><span className="demo-pill">{name(job.state)}</span></div><p className="demo-question">{job.message}</p><div className="demo-timeline">{job.events.filter(e=>e.phase==='started').map(e=><div key={e.id}><span className="demo-timeline-dot"/><strong>{e.name==='support-agent.chat'?'收到你的任务':e.name==='route'?'选择合适的业务助手':e.name==='ChatOpenAI'?'调用模型':e.name==='order'?'处理订单问题':e.name==='refund'?'核对退款问题':stepName(e.name)}</strong><small>{job.events.some(end=>end.id===e.id.replace(':started',':completed'))?'已完成':'执行中'}</small></div>)}{!job.events.length&&<p className="demo-muted">等待应用的实际调用记录。</p>}</div>{job.reply&&<div className="demo-reply"><span>客服助手回复</span><p>{job.reply}</p></div>}{job.error&&<p role="alert" className="demo-error">{job.error}</p>}</section>
    <section className="demo-panel"><div className="demo-section-title"><h2>调用依据</h2><small>{picked.length?'已选 '+picked.length+' 条':'默认使用本次全部证据'}</small><span className="demo-muted">{name(job.observation_state)}</span></div>{reusedLessons.length>0&&<div className="s9-reused-lessons"><div className="s9-reused-lessons-heading"><strong>引用的历史经验</strong><span>经验参考 · 非本次新证据</span></div><p>以下已审核经验来自同应用、同版本范围，用于调查参考，不替代本次运行的调用证据。</p>{reusedLessons.map((lesson,i)=><article key={lesson.id??i}><strong>{lesson.title}</strong><small>来源事故：{lesson.source_incident_id} · 范围：{typeof lesson.scope==='string'?lesson.scope:display(lesson.scope)}</small><p>{lesson.summary}</p></article>)}</div>}{job.application_reference&&<details className="demo-evidence"><summary>应用规则与工具依据</summary><p className="demo-muted">来自此次运行绑定的应用版本；随调用证据一起接受调查。</p><pre>{job.application_reference.content}</pre>{job.application_reference.files?.filter(file=>file.content).map(file=><details key={file.path}><summary>{file.path}{file.truncated ? "（内容有截断）" : ""}</summary><pre>{file.content}</pre></details>)}</details>}{job.observations.length?job.observations.map(o=><details className="demo-evidence" key={o.id}><summary><input aria-label={'选择证据 '+o.name} type="checkbox" disabled={!!job.runs.swarm||job.analysis_state==='running'} checked={picked.includes(o.id)} onClick={e=>e.stopPropagation()} onChange={e=>setEvidence(v=>e.target.checked?[...v,o.id]:v.filter(id=>id!==o.id))}/><CaretRight size={16}/><span>{stepName(o.name)}</span><small>{o.type==='GENERATION'?'模型':o.type==='TOOL'?'工具':'步骤'}</small></summary><div><h3>输入与上下文</h3><pre>{display(o.input)}</pre><h3>输出</h3><pre>{display(o.output)}</pre>{o.model&&<small>模型：{o.model}</small>}</div></details>):<p className="demo-muted">应用执行期间先展示实时步骤。Langfuse 同步后，可以展开调用的输入和结果。</p>}</section>
   </div><aside className="demo-governance"><section className="demo-panel demo-watch"><div className="demo-section-title"><h2><ShieldCheck size={20}/>Section9 观察</h2><span className="demo-pill">{name(job.observation_state)}</span></div>{job.findings.length?job.findings.map(f=><div className="demo-finding" key={f.key}><WarningCircle size={20}/><p>{f.summary}</p></div>):job.triage?<div className="s9-triage"><strong>{triageLabel(job.triage.state)}</strong><p>{job.triage.summary}</p></div>:<p className="demo-muted">{job.observation_state==='interrupted'?'观察连接中断，暂时无法判断。':'等待任务观察结果。'}</p>}{job.findings.length&&job.triage&&['expected_boundary','human_requested','manual_check_available','no_rule_finding'].includes(job.triage.state)?<div className="s9-triage s9-triage-secondary"><strong>{triageLabel(job.triage.state)}</strong><p>{job.triage.summary}</p></div>:null}<button className="demo-primary" disabled={busy||!investigationAllowed||job.state!=='completed'||job.observation_state!=='verified'||job.analysis_state==='running'||!!job.proposal} onClick={()=>act(()=>api('/tasks/'+job.id+'/investigate',{mode:'swarm',...(evidence.length?{evidence_ids:evidence}:{})}))}><UsersThree size={18}/>{!investigationAllowed?'事故已结案':job.analysis_state==='running'?'正在协作调查':['failed','interrupted'].includes(job.analysis_state)?'继续未完成的调查':'协作检查这次任务'}</button>{!investigationAllowed&&<p className="s9-closed-incident-note">事故已结案，不能启动或继续调查。</p>}{job.analysis_error&&<p className="demo-error" role="alert">{job.analysis_error}</p>}</section>
    <section className="demo-panel demo-office-panel"><div className="demo-section-title"><h2>协作办公室</h2><small>{job.collaboration?'EvoMap 已连接':'等待调查'}</small></div><OfficeScene investigation agents={officeAgents} events={officeEvents} generation={job.id} activeRunId={job.runs.swarm??null} incidentStatus={null} muted={false} connected={!!job.collaboration}/><div className="demo-office">{['investigator','reviewer','coordinator'].map((role,i)=>{const latest=collab.filter(e=>e.role===role).at(-1);const graphRoles=role==='investigator'?['investigator']:role==='reviewer'?['challenger_seed','challenger_review','reviewer']:['synthesizer','coordinator'];const roleTasks=tasks.filter(task=>graphRoles.includes(task.role));const roleComplete=roleTasks.length>0&&roleTasks.every(task=>task.state==='succeeded');const roleIncomplete=roleTasks.length>0?roleTasks.some(task=>task.state!=='succeeded'):latest?.kind==='handoff';const noPending= !tasks.some(task=>['claimed','running'].includes(task.state));const interrupted=['failed','interrupted'].includes(job.analysis_state)&&noPending&&roleIncomplete;return <button key={role} className={member===role?'active':''} onClick={()=>setMember(role)}><span className={'demo-desk desk-'+i}><UsersThree size={28}/></span><strong>{name(role)}</strong><small>{latest?.kind==='result'||roleComplete?'已提交结果':job.collaboration?.paused_members?.includes(role)?'已暂停':interrupted?'已中断，待继续':latest?.kind==='handoff'&&job.analysis_state==='running'?'正在处理':latest?'处理中':'待命'}</small></button>})}</div><p className="demo-role-description">{member==='investigator'?'调查员：结合业务上下文寻找原因。':member==='reviewer'?'复核员：独立提出反例，再检查调查解释。':'协调员：交接任务、汇总意见与处理建议。'}</p><div className="demo-messages">{collab.filter(e=>e.role===member).map((e,i)=><article key={e.remote_message_id??i}><small>{e.kind==='handoff'?'接收任务':e.kind==='takeover'?'接手任务':e.kind==='paused'?'成员暂停':'提交结果'} · {new Date(e.at).toLocaleTimeString()}</small><p>{e.summary}</p></article>)}{!collab.some(e=>e.role===member)&&<p className="demo-muted">该成员尚未开始工作。</p>}</div>{job.analysis_state==='running'&&<details className="demo-evidence"><summary>演练成员离线与接力</summary><p className="demo-muted">暂停一位成员，让另一位接手未完成的调查。已完成证据保留。</p><button disabled={busy} onClick={()=>act(()=>api('/tasks/'+job.id+'/members/investigator/pause',{}))}>暂停调查员</button></details>}{tasks.length>0&&<details className="demo-evidence"><summary>查看调查步骤</summary>{tasks.map(t=><p key={t.id}>{name(t.role)} · {name(t.state)}{t.result&&<span className="demo-step-summary">{t.result.summary}</span>}</p>)}</details>}</section>
    {job.proposal&&<section className="demo-panel"><div className="demo-section-title"><h2>处理建议</h2><small>第 {job.proposal.version} 版</small></div><p className="demo-proposal">{job.proposal.summary}</p>{job.review?<div className="demo-decision"><Check size={20}/><div>{job.review.decision==='approved'?'建议已认可':'已退回建议'}<p>{job.review.reason}</p>{job.review.decision==='rejected'&&<button disabled={busy||!investigationAllowed||job.analysis_state==='running'} onClick={()=>act(()=>api('/tasks/'+job.id+'/revise',{}))}>{investigationAllowed?'按意见重新调查':'事故已结案'}</button>}</div></div>:<><label className="demo-review-label" htmlFor="review-reason">你的审核意见</label><textarea id="review-reason" value={reason} onChange={e=>setReason(e.target.value)} placeholder="说明认可的依据，或需要补充的内容"/><div className="demo-review-actions"><button disabled={busy||!reason.trim()} onClick={()=>act(()=>api('/tasks/'+job.id+'/review',{proposal_sha256:job.proposal!.sha256,decision:'rejected',reason:reason.trim()}))}><X size={16}/>退回</button><button className="demo-primary" disabled={busy||!reason.trim()} onClick={()=>act(()=>api('/tasks/'+job.id+'/review',{proposal_sha256:job.proposal!.sha256,decision:'approved',reason:reason.trim()}))}><Check size={16}/>认可建议</button></div><small className="demo-muted">认可调查建议只表示接受其依据，不授权业务修改。</small></>}</section>}
    <ResolutionPanel taskId={job.id} resolution={job.resolution} targetPolicy={job.target_configuration?.policy} ready={resolutionReady} sourceCurrent={sourceCurrent} busy={busy} onBusyChange={setBusy} onRefresh={refresh}/>
   </aside></div>}
   {!!job?.history?.length&&<section className="demo-panel"><h2>之前的方案</h2>{job.history.map((h,i)=><details className="demo-evidence" key={i}><summary>第 {h.proposal.version} 版 · {h.review?.decision==='rejected'?'已退回':'已审核'}</summary><p>{h.proposal.summary}</p><p className="demo-muted">审核意见：{h.review?.reason}</p></details>)}</section>}
   {job?.runs.swarm&&job.analysis_state!=='running'&&<section className="demo-panel demo-compare"><div className="demo-section-title"><div><h2>一个助手，与一个协作团队</h2><p className="demo-muted">用相同业务证据进行调查，保留两边的结果与消耗。</p></div>{(!job.runs.single||job.investigations?.single?.task_graph.tasks.some(t=>t.state!=='succeeded'))&&<button disabled={busy||!investigationAllowed} onClick={()=>act(()=>api('/tasks/'+job.id+'/investigate',{mode:'single'}))}>{!investigationAllowed?'事故已结案':job.runs.single?'继续单助手对比':'运行单助手对比'}<ArrowRight size={18}/></button>}{!investigationAllowed&&<small className="s9-closed-incident-note">事故已结案，不能启动或继续调查。</small>}</div><div className="demo-comparison-grid">{(['single','swarm'] as const).map(mode=>{const r=job.investigations?.[mode];const c=job.comparison?.[mode];const final=r?.task_graph.tasks.find(t=>t.role==='synthesizer')?.result;const usage=r?.model_usage??[];const oldRuns=(job.run_history?.[mode]??[]).filter(entry=>entry.run_id!==job.runs[mode]);return <article key={mode}><h3>{mode==='single'?'单助手':'EvoMap 协作团队'}</h3><p>{final?.summary??(r?'调查尚未完成':'尚未运行')}</p>{c&&<small><Clock size={14}/>{c.elapsed_s} 秒 · {usage.some(x=>x.actual_tokens===null)?'用量未完全确认':usage.reduce((s,x)=>s+(x.actual_tokens??0),0)+' tokens'}</small>}{oldRuns.length>0&&<details className="s9-run-history"><summary>历史中断记录（{oldRuns.length} 次）</summary>{oldRuns.map((entry,index)=><div className="s9-run-history-entry" key={entry.run_id??index}><strong>{entry.state==='blocked_policy_changed'?'策略已更新，旧运行保留为未完成记录':'历史调查记录'}</strong><p>已知用量 {entry.known_total_tokens??'未知'} tokens · 用量未知 {entry.usage_unknown_count??'未知'} 条</p><small>当时预算 {entry.token_limit} tokens · 策略版本 r{entry.policy_revision}{entry.replaced_at?` · ${new Date(entry.replaced_at).toLocaleString()}`:''}</small></div>)}</details>}</article>})}</div></section>}
   <footer className="demo-footer">Section9 · 每个判断，都能回到依据。<a href="/">原工作台</a></footer>
  </main></div></div>
}
