import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Archive, ArrowClockwise, Brain, CheckCircle, CloudSlash, Command, Gauge, GitBranch, Lightning, Pause, Play, Plug, Pulse, Robot, ShieldCheck, SlidersHorizontal, Sparkle, TerminalWindow, UserCircle, Warning, X } from '@phosphor-icons/react'
import './styles.css'
import './overrides.css'
import './scene.css'
import './matrix.css'
import './sprite.css'
import './sprite-fix.css'
import './product-scope.css'
import OfficeScene from './OfficeScene'
import './playbook.css'
import './compact.css'
import './product-finish.css'
import { ShowcasePage, PairConsole } from './ShowcasePage'

type Agent={id:string;role:string;name:string;status:string;heartbeat_at:string|null;task_id:string|null;detail:string;capabilities:string[]}
type Incident={id:string;run_id:string;status:string;opened_at:string;closed_at:string|null;symptoms:string[];scenario:string;plan:any;verification:any;elapsed_s:number|null}
type EventItem={event_id:string;sequence:number;event_type:string;occurred_at:string;run_id:string|null;incident_id:string|null;producer:string;generation:string;payload:Record<string,any>}
type State={generation:string;autonomy:'L0'|'L1'|'L2';muted:boolean;monitoring:boolean;memory_enabled:boolean;config:any;agents:Agent[];incident:Incident|null;runs:any[];metrics:any;dependencies:any;playbooks:any[];events:EventItem[];attract:{enabled:boolean;cycle:number;auto_running?:boolean;url?:string};model:string;version:string}
const emptyState:State={generation:'?',autonomy:'L2',muted:false,monitoring:false,memory_enabled:false,config:{revision:'?',prompt_version:'unknown',context_multiplier:1,max_output_tokens:256,retry_limit:3,retry_on_terminal:false},agents:[],incident:null,runs:[],metrics:{total:0,success:0,failures:0,usage_tokens:0},dependencies:{},playbooks:[],events:[],attract:{enabled:false,cycle:0},model:'unknown',version:'0.1.0'}
const api=async <T,>(path:string, init?:RequestInit):Promise<T>=>{const r=await fetch(path,{...init,headers:{'Content-Type':'application/json',...(init?.headers||{})}});let b:any={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b?.error?.message||b?.detail||`HTTP ${r.status}`);return b}
const post=(path:string,body:any={},options?:RequestInit)=>api<any>(path,{...options,method:'POST',body:JSON.stringify(body)})
const put=(path:string,body:any)=>api<any>(path,{method:'PUT',body:JSON.stringify(body)})
const clock=(v?:string|null)=>v?new Date(v).toLocaleTimeString('zh-CN',{hour12:false}):'—'
const safeText=(v:any):string=>{if(v===null||v===undefined)return '未知';if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')return String(v);if(Array.isArray(v))return v.map(safeText).join(' · ');try{return JSON.stringify(v)}catch{return '不可序列化'}}
const autonomyLabels:Record<string,string>={L0:'仅建议',L1:'确认后执行',L2:'自动处理'}
const statusLabels:Record<string,string>={idle:'待命',working:'处理中',running:'处理中',starting:'启动中',resuming:'恢复中',paused:'已暂停',offline:'离线',available:'可用',local:'本地可用',configured:'已配置',degraded:'连接不稳定',local_only:'仅本机可用',pending_auth:'等待授权发布',published:'已发布',pending:'待确认',proposed:'待确认',approved:'已确认',completed:'已完成',resolved:'已恢复',failed:'未完成',error:'读取失败',timeout:'响应超时',cancelled:'已取消',reset:'已重置',interrupted:'已中断',blocked:'等待处理',rejected:'已拒绝',unconfigured:'尚未配置',disabled:'未启用',injected:'已发现',diagnosing:'分析中',repairing:'处理中',verifying:'验收中',waiting:'等待确认',passed:'已通过',skipped:'未执行',unknown:'状态未知'}
const scenarioLabels:Record<string,string>={prompt:'回答偏离预期',cost:'处理成本升高',loop:'重复操作未结束',composite:'多项异常同时发生'}
const symptomLabels:Record<string,string>={quality_mismatch:'回答不符合业务规则',cost_high:'处理成本升高',tool_stalled:'处理动作停滞',prompt_degraded:'回答偏离预期'}
const actionLabels:Record<string,string>={set_prompt_revision:'恢复回答规则',apply_context_budget:'收紧调用预算',apply_retry_policy:'限制重复调用',apply_config_bundle:'同步修复多项配置'}
const rowLabels:Record<string,string>={single:'独立助手',muted:'暂停协作通信',swarm:'协作团队',memory:'协作团队 + 处置经验',memory_jev:'协作团队 + 压缩记忆（未启用）'}
const roleLabels:Record<string,string>={sentry:'监测员',diagnoser:'诊断员','fixer-a':'修复员 A','fixer-b':'修复员 B',verifier:'验收员',single:'独立助手',cost:'成本专家'}
const eventLabels:Record<string,string>={
 'incident.opened':'发现需要关注的情况','incident.updated':'情况有新进展','incident.closed':'情况已关闭','run.started':'开始处理','run.completed':'处理完成','run.failed':'处理未完成',
 'request.started':'收到咨询','request.completed':'回复已生成','model.started':'开始分析','model.completed':'分析完成','plan.proposed':'提出处理方案','plan.approved':'处理方案已确认',
 'action.started':'开始执行','action.completed':'执行完成','verification.started':'开始验收','verification.completed':'验收完成','agent.joined':'协作者已加入','agent.paused':'协作者已暂停','agent.resumed':'协作者已恢复',
 'communication.muted':'协作通信已禁言','memory.enabled':'处置经验已启用','memory.disabled':'处置经验已关闭','reset.completed':'本轮已重置','dependency.changed':'服务状态变化','agent.status':'成员状态更新','agent.message':'协作消息','diagnosis.created':'原因分析完成','plan.created':'提出处理方案','tool.applied':'执行了修复','task.claimed':'已认领任务','run.terminal':'处理结束','message.dropped':'消息已被禁言拦截'
}
const displayStatus=(v:any)=>statusLabels[String(v)]||'状态未知'
const displayScenario=(v:any)=>scenarioLabels[String(v)]||'需要关注的情况'
const displayEvent=(v:any)=>eventLabels[String(v)]||'现场动态'
const dependencyLabels:Record<string,string>={model:'推理服务',langfuse:'追踪记录',collector:'遥测采集',evomap:'协作服务',jev:'记忆压缩'}
const displayEventMessage=(v:any)=>{if(v===null||v===undefined||v==='')return '处理状态已更新';const s=String(v);const dependency=s.match(/^(model|langfuse|collector|evomap|jev)\s+(\w+)$/);if(dependency)return `${dependencyLabels[dependency[1]]} · ${displayStatus(dependency[2])}`;if(/(?:event_|run_|prompt_version|config_revision|generation|model\.|SSE|GEN|REV|hash|trace|status=|code=)/i.test(s))return '处理记录已更新，详情见事件复盘';return displayDetail(s)}
const displayRole=(a:Agent)=>roleLabels[a.id]||a.name||'专项助手'
const displayDetail=(v:any):string=>{if(v===null||v===undefined||v==='')return '暂无说明';if(Array.isArray(v))return v.map(displayDetail).join('、');if(typeof v==='number')return String(v);if(typeof v==='boolean')return v?'是':'否';if(typeof v==='string'){if(/心跳失联/.test(v))return '离线，等待重新连接';let s=v.replace(/\b(?:L[012]|GEN|REV|SSE|run_[a-z0-9_-]+|prompt_version|event_[a-z0-9_-]+)\b/gi,'').replace(/\s{2,}/g,' ').trim();Object.entries(symptomLabels).forEach(([k,label])=>{s=s.replace(new RegExp(k,'gi'),label)});return s||'暂无说明'}return '已有记录'}
const actionLabel=(v:any):string=>{if(Array.isArray(v))return v.map(actionLabel).join('、');if(typeof v==='string')return actionLabels[v]||displayDetail(v);if(v&&typeof v==='object')return actionLabels[v.type]||displayDetail(v.title||v.description||v.action||v.name);return '按当前方案处理'}
const checkNames:Record<string,string>={heldout_semantic_policy:'期限内退货规则',heldout_outside_return_window:'超过退货期限',unaffected_product_fact:'商品信息保持正确',semantic_policy:'退货规则',cost_budget:'单次调用预算',no_stalled_requests:'没有停滞的调用',terminal_tool_stops:'查询结束后停止调用',revision_unchanged_at_close:'验收配置持续生效',whole_run_budget:'本轮总预算',acceptance_contract_complete:'验收项目完整'}
const checkSummary=(x:any):string=>{if(x.actual?.answer)return x.actual.answer;if(x.name==='revision_unchanged_at_close')return x.passed===true?'结案时仍使用本次验收的配置。':'结案时的配置与验收时不一致。';if(x.name==='acceptance_contract_complete')return `需要 ${Array.isArray(x.expected)?x.expected.length:'全部'} 项检查，已记录 ${Array.isArray(x.actual)?x.actual.length:'相关'} 项。`;if(x.name==='no_stalled_requests')return `停滞调用：${typeof x.actual==='number'?x.actual:'未知'} 次`;if(x.name==='cost_budget')return x.passed===true?'各项请求的输入、输出和总用量均在限额内。':'存在超出限额或用量不明的请求。';if(x.name==='whole_run_budget')return `本轮预算上限：${typeof x.expected==='number'?x.expected.toLocaleString():'未知'} Token`;if(x.name==='terminal_tool_stops')return x.passed===true?'查询完成后停止调用。':'查询结束后的调用检查未通过。';return x.passed===true?'结果符合本次验收要求。':x.passed===false?'结果未满足本次验收要求。':'结果尚未确认。'}
const playbookTitle=(x:any)=>({seed_quality_prompt:'恢复客服回答',seed_cost_budget:'控制处理成本',seed_stalled_retry:'结束无效重试',seed_composite_repair:'恢复多项异常'} as Record<string,string>)[x.id]||displayDetail(x.title).replace('已验证本地修复','恢复经验')
function App(){
 if(window.location.pathname.startsWith('/showcase')) return <ShowcasePage />
 const [state,setState]=useState<State>(emptyState),[offline,setOffline]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState<'office'|'runs'|'playbooks'|'score'>('office'),[chat,setChat]=useState(''),[messages,setMessages]=useState<{from:string;text:string;time:string}[]>([]),[busy,setBusy]=useState<string|null>(null),[liveEvents,setLiveEvents]=useState<EventItem[]>([])
 const chatEpoch=useRef(0),chatAbort=useRef<AbortController|null>(null)
 const eventSeq=useRef(0)
 const refresh=useCallback(async()=>{try{const s=await api<State>('/api/state');setState(s);setOffline(false);setError('')}catch(e){setOffline(true);setError((e as Error).message)}},[])
 useEffect(()=>{refresh();const timer=setInterval(refresh,12000);return()=>clearInterval(timer)},[refresh])
 const [sseStatus,setSseStatus]=useState<'connecting'|'open'|'reconnecting'>('connecting')
 useEffect(()=>{let es:EventSource|undefined;let timer:number|undefined;try{es=new EventSource('/api/events?after='+eventSeq.current);es.onopen=()=>setSseStatus('open');es.addEventListener('update',(ev)=>{const x=JSON.parse((ev as MessageEvent).data) as EventItem;eventSeq.current=x.sequence;setLiveEvents(v=>[x,...v].slice(0,30));window.clearTimeout(timer);timer=window.setTimeout(refresh,300)});es.onerror=()=>setSseStatus('reconnecting')}catch{setSseStatus('reconnecting')}return()=>{window.clearTimeout(timer);es?.close()}},[refresh])
 const act=async(key:string,fn:()=>Promise<any>)=>{setBusy(key);setError('');try{await fn();await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(null)}}
 const sendChat=async()=>{if(!chat.trim()||busy==='reset')return;const q=chat.trim();setChat('');const epoch=++chatEpoch.current;const controller=new AbortController();chatAbort.current=controller;setMessages(m=>[...m,{from:'operator',text:q,time:new Date().toISOString()}]);setBusy('chat');setError('');try{const r=await post('/api/chat',{message:q},{signal:controller.signal});if(epoch!==chatEpoch.current)return;if(r.status==='cancelled'){setMessages(m=>[...m,{from:'系统',text:'本轮已重置，请求已取消。',time:new Date().toISOString()}]);return}if(r.status==='error'||r.status==='timeout')throw new Error(`客服请求${r.status==='timeout'?'超时':'失败'}：未生成正常回答`);setMessages(m=>[...m,{from:'小智',text:r.answer||r.structured?.answer||'模型未返回可显示内容',time:new Date().toISOString()}]);}catch(e){if(epoch===chatEpoch.current&&(e as Error).name!=='AbortError')setError((e as Error).message)}finally{if(epoch===chatEpoch.current){chatAbort.current=null;setBusy(v=>v==='chat'?null:v)}}}
 const resetLab=async()=>{if(busy==='reset')return;chatEpoch.current++;chatAbort.current?.abort();chatAbort.current=null;setBusy('reset');setError('');try{await post('/api/reset',{});setMessages(m=>[...m,{from:'系统',text:'本轮已重置，请求已取消。',time:new Date().toISOString()}]);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(v=>v==='reset'?null:v)}}
 const inject=(scenario:string)=>{if(state.memory_enabled&&state.muted){setError('复用处置经验时需要开启协作通信，请先关闭禁言或暂停经验复用。');return}return act('inject-'+scenario,()=>post('/api/inject',{scenario,condition:state.muted?'muted':state.memory_enabled?'memory':'swarm'}))}
 const officeEvents=[...new Map([...liveEvents,...(state.events||[])].map(e=>[String(e.sequence),e])).values()].sort((a,b)=>Number(b.sequence)-Number(a.sequence))
 const latest=officeEvents.slice(0,10)
 const fixer=state.agents.find(a=>a.id==='fixer-a'), specialist=state.agents.find(a=>a.id.includes('cost'))
 return <div className="app-shell">
   <header className="topbar"><div className="brand"><span className="brand-mark">S9</span><div><strong>公安九课</strong><small>让每次协作看得见</small></div></div><div className="top-meta"><span className={offline?'offline':'online'}><i/> {offline?'暂时离线 · 正在恢复':'服务已连接'}</span><span className="connection-state">{sseStatus==='open'?'实时更新中':sseStatus==='reconnecting'?'正在重新连接':'正在连接'}</span><button className="icon-btn" title="刷新状态" aria-label="刷新状态" onClick={refresh}><ArrowClockwise size={18}/></button></div></header>
   {error&&<div className="error-banner"><Warning size={18}/><span>{error}</span><button onClick={()=>setError('')}><X size={16}/></button></div>}
   <div className="toolbar"><div className="tabs"><button className={tab==='office'?'active':''} onClick={()=>setTab('office')}><Command/>实时监护</button><button className={tab==='runs'?'active':''} onClick={()=>setTab('runs')}><Pulse/>处理记录</button><button className={tab==='playbooks'?'active':''} onClick={()=>setTab('playbooks')}><Archive/>处置经验</button><button className={tab==='score'?'active':''} onClick={()=>setTab('score')}><Gauge/>验收评分</button></div><div className="toolbar-right"><span className="model-chip"><Brain size={15}/> 当前应用</span><button className="ghost" onClick={resetLab} disabled={busy==='reset'}><ArrowClockwise/>{busy==='reset'?'重置中…':'重新开始本轮'}</button></div></div>
   {tab==='office'?<main className="workspace">
      <section className="left-column"><div className="section-heading"><div><span className="eyebrow">实时监护</span><h1>当前应用的处理现场</h1></div><div className="status-led"><span className="pulse"/>{state.monitoring?'正在监护':'等待开始'}</div></div>
       <div className="flow-chain"><div className="flow-step active"><b>01</b><strong>收到咨询</strong><small>当前应用的用户问题</small></div><i>→</i><div className={'flow-step '+(state.incident?'active':'')}><b>02</b><strong>发现情况</strong><small>{state.incident?(state.incident.symptoms||[]).map(displayDetail).join(' / '):'等待新的情况'}</small></div><i>→</i><div className={'flow-step '+(state.incident?.plan?'active':'')}><b>03</b><strong>协作处理</strong><small>{state.incident?.plan?'正在形成处理方案':'等待判断'}</small></div><i>→</i><div className={'flow-step '+(state.incident?.verification?.passed===true||state.incident?.verification?.passed===false?'active':'')}><b>04</b><strong>结果确认</strong><small>{state.incident?.verification?.passed===true?'已通过':state.incident?.verification?.passed===false?'未通过':'等待结果'}</small></div></div>
              <OfficeScene agents={state.agents} events={officeEvents} generation={state.generation} incidentStatus={state.incident?.status||null} activeRunId={state.incident?.run_id||state.incident?.id||null} muted={state.muted} connected={!offline}/>
       <div className="inject-strip"><div><span className="eyebrow">情境演练</span><p>为当前应用选择一种异常。</p></div><div className="inject-buttons"><button onClick={()=>inject('prompt')} disabled={!!busy}><Warning/>回答偏离预期</button><button onClick={()=>inject('cost')} disabled={!!busy}><Lightning/>处理成本升高</button><button onClick={()=>inject('loop')} disabled={!!busy}><ArrowClockwise/>重复操作未结束</button><button onClick={()=>inject('composite')} disabled={!!busy}><GitBranch/>多项情况同时发生</button></div></div>
      <div className="lower-grid"><Panel title="客服窗口" icon={<UserCircle/>}><div className="chat-log">{messages.length===0&&<div className="empty">还没有本轮对话。输入一个用户问题开始。</div>}{messages.map((m,i)=><div className={'msg '+m.from} key={i}><span>{m.from==='operator'?'你':m.from==='系统'?'系统':'小智'} · {clock(m.time)}</span><p>{m.text}</p></div>)}</div><div className="chat-input"><input value={chat} onChange={e=>setChat(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendChat()} placeholder="输入用户的售后问题…" aria-label="客服消息"/><button onClick={sendChat} disabled={busy==='chat'||!chat.trim()}>{busy==='chat'?'处理中…':'发送'}</button></div></Panel><Panel title="现场动态" icon={<Pulse/>}><div className="event-feed">{latest.length===0&&<div className="empty">等待新的处理动态…</div>}{latest.map(e=><div className="event-row" key={e.sequence}><div><strong>{displayEvent(e.event_type)}</strong><small>{displayEventMessage(e.payload?.summary||e.payload?.message||e.payload?.reason)}</small></div><time>{clock(e.occurred_at)}</time></div>)}</div></Panel></div>
      </section>
      <aside className="right-column"><section className="scope-section scope-primary"><div className="scope-heading"><div><span className="eyebrow">当前应用</span><h2>实时处理控制</h2></div><span className="scope-chip">仅作用于当前应用</span></div><p className="scope-note">设置本轮团队的处理权限。</p><Panel title="处理方式" icon={<SlidersHorizontal/>}><div className="control-line"><span>自动化程度</span><div className="segmented">{(['L0','L1','L2'] as const).map(l=><button aria-label={autonomyLabels[l]} key={l} className={state.autonomy===l?'selected':''} onClick={()=>act(l,()=>put('/api/autonomy',{level:l}))}>{autonomyLabels[l]}</button>)}</div></div><div className="control-line"><span>协作通信</span><button className={'toggle '+(state.muted?'on':'')} onClick={()=>act('mute',()=>put('/api/communication',{muted:!state.muted}))}><i/>{state.muted?'已禁言':'正常通信'}</button></div><div className="control-line"><span>处置经验</span><button className={'toggle '+(state.memory_enabled?'on':'')} onClick={()=>act('memory',async()=>{const r=await put('/api/memory',{enabled:!state.memory_enabled});if(typeof r.enabled==='boolean')setState(s=>({...s,memory_enabled:r.enabled}))})}><i/>{state.memory_enabled?'本轮启用':'未启用'}</button></div><div className="control-line"><span>演练导览</span><button className={'toggle '+(state.attract?.enabled?'on':'')} onClick={()=>act('attract',()=>put('/api/attract',{enabled:!state.attract?.enabled}))}><i/>{state.attract?.enabled?(state.attract.auto_running===false&&state.attract.cycle>=3?'导览完成':'进行中'):'未开始'}</button></div>{state.attract?.enabled&&<a className="attract-link" href={state.attract.url||'http://127.0.0.1:9020'} target="_blank" rel="noreferrer">打开独立导览 · 最多 3 轮</a>}<div className="control-line"><span>推理服务</span><span className={'value dep-'+(state.dependencies?.model?.status||'unknown')}>{displayStatus(state.dependencies?.model?.status)} · 远程推理</span></div></Panel>
      <details className="team-details"><summary>团队成员 <span>{state.agents.length} 位</span></summary><Panel title="成员状态" icon={<Robot/>}><div className="agents">{state.agents.map(a=><div className="agent" key={a.id}><span className={'agent-dot '+a.status}/><div><strong>{displayRole(a)}</strong><em>{displayStatus(a.status)}</em><small>{displayDetail(a.detail)} · {clock(a.heartbeat_at)}</small></div><span className="agent-state">{displayStatus(a.status)}</span></div>)}{state.agents.length===0&&<div className="empty">协作者状态尚未返回。</div>}</div><div className="agent-actions"><button onClick={()=>act('join',()=>post('/api/agents/join'))}><Sparkle/>邀请成本专家</button>{fixer&&<><button onClick={()=>act('pause',()=>post('/api/agents/fixer-a/pause'))} disabled={fixer.status==='paused'}><Pause/>暂停修复员</button><button onClick={()=>act('resume',()=>post('/api/agents/fixer-a/resume'))} disabled={fixer.status!=='paused'}><Play/>恢复修复员</button></>}</div></Panel></details>
      <Panel title="当前异常" icon={<ShieldCheck/>}><IncidentCard incident={state.incident} busy={busy} onApprove={()=>act('approve',()=>post('/api/approve',{plan_id:state.incident?.plan?.id||''}))} onFencing={()=>act('fencing',()=>post('/api/demo/fencing'))}/></Panel></section><section className="scope-section scope-pair"><div className="scope-heading"><div><span className="eyebrow">对照实验</span><h2>对照实验控制</h2></div><span className="scope-chip scope-pair-chip">固定自动处理 · 独立运行</span></div><p className="scope-note">在相同条件下，比较协作团队与独立助手。</p><PairConsole/></section>
      <details className="advanced-details"><summary><Plug/>查看运行保障状态</summary><div className="deps">{Object.entries(state.dependencies||{}).map(([k,v]:any)=><div key={k}><span className={'dep-dot '+v.status}/><span>{k==='langfuse'&&v.url?<a href={v.url} target="_blank" rel="noreferrer">记录服务</a>:'系统服务'}</span><small>{displayStatus(v.status)} · {displayDetail(v.detail)}</small></div>)}</div></details>
      </aside>
 </main>:tab==='playbooks'?<PlaybookView/>:<DataView tab={tab} state={state} refresh={refresh}/>}<footer><span><TerminalWindow/> 公安九课</span><span>处理有记录，结果可复查</span></footer>
 </div>
}
function Panel({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="panel"><div className="panel-title"><span>{icon}</span><strong>{title}</strong><i/></div>{children}</section>}
function IncidentCard({incident,busy,onApprove,onFencing}:{incident:Incident|null;busy:string|null;onApprove:()=>void;onFencing:()=>void}){if(!incident)return <div className="empty incident-empty"><CheckCircle size={24}/>目前没有需要处理的情况<div className="empty-sub">可从上方情境演练开始一次处理。</div><details className="rehearsal-details"><summary>更多演练</summary><button onClick={onFencing} disabled={!!busy}><GitBranch/>模拟成员失联与接管</button></details></div>;const approvable=incident.plan?.status==='proposed'||incident.plan?.status==='pending';const passed=incident.verification?.passed;const acceptance=passed===true?'通过':passed===false?'未通过':'待确认';return <div className="incident-card"><div className="incident-head"><span className="severity">{displayStatus(incident.status)}</span><span className="incident-clock">{clock(incident.opened_at)}</span></div><h3>{displayScenario(incident.scenario)}</h3><p>{incident.symptoms?.map(displayDetail).join(' / ')||'正在补充情况说明'}</p><div className="incident-meta"><span>开始 {clock(incident.opened_at)}</span><span>用时 {incident.elapsed_s==null?'未知':incident.elapsed_s+' 秒'}</span><span className={'acceptance acceptance-'+acceptance}>{`验收 ${acceptance}`}</span></div>{incident.plan&&<div className="plan"><span>处理方案 · {displayStatus(incident.plan.status)}</span><p className="plan-rationale">{displayDetail(incident.plan.rationale)}</p><div className="plan-actions">{(incident.plan.actions||[]).slice(0,3).map((a:any,i:number)=><span key={i}>{actionLabel(a)}</span>)}</div><button onClick={onApprove} disabled={busy==='approve'||!approvable}>{approvable?'确认处理方案':incident.plan.status==='approved'?'方案已确认':'已处理'}</button></div>}</div>}
function DataView({tab,state,refresh}:{tab:string;state:State;refresh:()=>void}){
 const [data,setData]=useState<any>(null),[err,setErr]=useState(''),[detail,setDetail]=useState<any>(null),[detailKind,setDetailKind]=useState(''),[selectedVersion,setSelectedVersion]=useState('')
 const dataSeq=useRef(0)
 const stateKey=useMemo(()=>JSON.stringify({generation:state.generation,muted:state.muted,memory_enabled:state.memory_enabled,incident:state.incident&&{id:state.incident.id,status:state.incident.status,run_id:state.incident.run_id},metrics:state.metrics,agents:state.agents.map(a=>[a.id,a.status,a.task_id])}),[state])
 useEffect(()=>{let alive=true;let timer:number|undefined;const controller=new AbortController();const base=tab==='runs'?'/api/runs':tab==='playbooks'?'/api/playbooks':'/api/scoreboard';const p=tab==='score'&&selectedVersion?`${base}?version=${encodeURIComponent(selectedVersion)}`:base;const load=async()=>{const seq=++dataSeq.current;try{const d=await api<any>(p,{signal:controller.signal});if(alive&&seq===dataSeq.current){setData(d);setErr('')}}catch(e){if(alive&&(e as Error).name!=='AbortError')setErr((e as Error).message)}};setData(null);setErr('');load();timer=window.setInterval(load,3000);return()=>{alive=false;controller.abort();window.clearInterval(timer)}},[tab,stateKey,selectedVersion])
 const openDetail=async(id:string,kind:string)=>{setDetailKind(kind);setDetail(null);try{if(kind==='run'){const [run,rca]=await Promise.all([api<any>(`/api/runs/${id}`),api<any>(`/api/rca/${id}`)]);setDetail({...run,...rca,events:run.events||[],evidence:rca.evidence||[],verification:run.verification||rca.verification})}else setDetail(await api<any>(`/api/rca/${id}`))}catch(e){setDetail({error:(e as Error).message})}}
 if(err)return <main className="data-view"><div className="empty"><CloudSlash size={30}/>{err}<button onClick={refresh}>重试</button></div></main>
 if(!data)return <main className="data-view"><div className="loading"><span/>正在读取记录…</div></main>
 const effectiveVersion=selectedVersion||data.selected_version||data.current_version||''
 return <main className="data-view"><div className="data-heading"><div><span className="eyebrow">{tab==='runs'?'处理记录':tab==='playbooks'?'处置经验':'验收评分'}</span><h1>{tab==='runs'?'处理记录':tab==='playbooks'?'处置经验':'验收评分'}</h1></div><span className="data-note">实时更新 · {new Date().toLocaleTimeString('zh-CN',{hour12:false})}</span></div>{tab==='score'?<ScoreMatrix data={data} openDetail={openDetail} selectedVersion={effectiveVersion} onVersionChange={setSelectedVersion}/>:<div className="data-list">{(data.items||[]).length===0&&<div className="empty">目前还没有已记录的处理结果。</div>}{(data.items||[]).map((x:any,i:number)=><article key={x.id||i} onClick={()=>tab==='runs'&&x.id&&openDetail(x.id,'run')}><div className="list-id">第 {i+1} 条</div><div><h3>{displayScenario(x.title||x.scenario||x.status)}</h3><p>{displayDetail(x.summary||x.symptoms?.join(' / ')||x.source)}</p></div><div className="record-state"><strong>{displayStatus(x.status)}</strong><time>{clock(x.opened_at||x.created_at)}</time></div>{tab==='runs'&&<button className="detail-button">查看处理详情</button>}</article>)}</div>}{detail&&<DetailDrawer detail={detail} kind={detailKind} onClose={()=>setDetail(null)}/>}</main>
}
function ScoreMatrix({data,openDetail,selectedVersion,onVersionChange}:{data:any;openDetail:(id:string,kind:string)=>void;selectedVersion:string;onVersionChange:(version:string)=>void}){const rows=data.rows||[];const scenarios=['prompt','cost','loop','composite'];const [selected,setSelected]=useState<string[]|null>(null);const versions=Array.isArray(data.versions)?data.versions:[];const limitation='独立实验结果；失败和未知用量均保留，样本不足时不作优劣判断。';return <><div className="score-controls"><label htmlFor="score-version">验收批次</label><select id="score-version" value={selectedVersion} onChange={e=>{setSelected(null);onVersionChange(e.target.value)}}>{versions.length===0&&<option value={selectedVersion}>历史记录（来源不完整）</option>}{versions.map((v:any,i:number)=><option key={v.id} value={v.id}>第 {i+1} 批 · {v.n??0} 次处理</option>)}</select><small>{limitation}</small></div><div className="score-matrix"><div className="matrix-head"><span>处理情况</span>{scenarios.map(s=><span key={s}>{scenarioLabels[s]}</span>)}</div>{rows.map((r:any)=><div className="matrix-row" key={r.id}><strong>{rowLabels[r.id]||displayDetail(r.label)}</strong>{scenarios.map(s=>{const c=(r.cells||[]).find((x:any)=>x.scenario===s);const ids=c?.run_ids||[];return <button className="matrix-cell" key={s} disabled={!ids.length} onClick={()=>setSelected(ids)}><b>{c?.n===0||!c?.n?'待测':`${c.n} 次`}</b><small>{c?.n?`未通过 ${c.failures??'未知'} 次 · 用时 ${c.median_s==null?'未知':c.median_s+' 秒'}`:'尚未验收'}</small><small>{c?.n?(c.usage_tokens==null?'资源用量未知':`资源用量 ${c.usage_tokens} token`): '尚无验收记录'}</small>{c?.n&&c?.unknown_usage_runs>0&&<small>{c.unknown_usage_runs} 次资源用量未知</small>}</button>})}</div>)}</div>{selected&&<div className="run-picker"><div className="run-picker-head"><strong>选择处理记录</strong><button onClick={()=>setSelected(null)}>关闭</button></div>{selected.map((id,i)=><button key={id} onClick={()=>openDetail(id,'run')}>第 {i+1} 条处理记录</button>)}</div>}</>}
function DetailDrawer({detail,kind,onClose}:{detail:any;kind:string;onClose:()=>void}){const [loading]=useState(!detail);if(loading)return <div className="detail-drawer"><div className="drawer-head"><strong>读取详情</strong><button onClick={onClose}>关闭</button></div><div className="loading"><span/>正在读取已记录内容…</div></div>;const summary=typeof detail.summary==='string'?displayDetail(detail.summary):'暂无摘要';const events=Array.isArray(detail.events)?detail.events:[];const evidence=Array.isArray(detail.evidence)?detail.evidence:[];const displayEvents=events.length?events:[...new Map(evidence.map((x:any)=>[x.event_id||JSON.stringify(x),x])).values()];const checks=Array.isArray(detail.checks)?detail.checks:(Array.isArray(detail.verification?.checks)?detail.verification.checks:[]);const actions=Array.isArray(detail.actions)?detail.actions:(Array.isArray(detail.plan?.actions)?detail.plan.actions:[]);return <div className="detail-drawer"><div className="drawer-head"><strong>{kind==='rca'?'事件复盘 / 处理证据':'处理详情'}</strong><button onClick={onClose}>关闭</button></div>{detail.error?<div className="empty"><CloudSlash size={25}/>暂时无法读取这条记录<button onClick={onClose}>返回</button></div>:<div className="drawer-body"><div className="detail-title">{displayDetail(detail.title)||'处理记录'}</div><div className="detail-kv"><span>处理状态</span>{displayStatus(detail.status)}</div><div className="detail-kv"><span>资源记录</span>{detail.usage==null&&detail.usage_tokens==null?'未知 / 未测':'已记录'}</div>{summary&&<p className="detail-summary">{summary}</p>}<h4>验收结果</h4>{checks.length?checks.map((x:any,i:number)=><div className={'detail-check '+(x.passed?'passed':'failed')} key={i}><strong>{x.passed===true?'已通过':x.passed===false?'未通过':'待测'} · {checkNames[x.name]||'业务检查'}</strong><small>{checkSummary(x)}</small></div>):<div className="detail-muted">暂无验收记录</div>}<details className="raw-record"><summary>查看原始记录</summary><h4>现场动态</h4>{displayEvents.map((x:any,i:number)=><div className="detail-event" key={x.event_id||i}><code>{safeText(x.event_type||'event')}</code><span>{safeText(x.producer||'记录服务')} · {clock(x.occurred_at)} · {safeText(x.event_id||'—')}</span><p>{safeText(x.payload?.summary||x.payload?.message||x.summary||x)}</p></div>)}<h4>处理动作</h4><pre>{safeText(actions)}</pre><pre>{safeText(detail)}</pre></details></div>}</div>}
function PlaybookView(){const [data,setData]=useState<any>(null),[error,setError]=useState('');useEffect(()=>{api<any>('/api/playbooks').then(setData).catch(e=>setError(e.message))},[]);if(error)return <main className="data-view"><div className="empty"><CloudSlash size={26}/>暂时无法读取处置经验<button onClick={()=>location.reload()}>重试</button></div></main>;if(!data)return <main className="data-view"><div className="loading"><span/>正在读取处置经验…</div></main>;return <main className="data-view"><div className="data-heading"><div><span className="eyebrow">处置经验</span><h1>处置经验库</h1></div></div><div className="playbook-list">{(data.items||[]).length===0&&<div className="empty">还没有可复用的处置经验；完成一次成功处理后会出现在这里。</div>}{(data.items||[]).map((x:any,i:number)=><article className="playbook-card" key={x.id||i}><div className="playbook-top"><span>{displayStatus(x.publish_state||x.status?.publish_state)}</span><span>第 {i+1} 条</span></div><h3>{playbookTitle(x)||'待命名的处置经验'}</h3><p>{displayDetail(x.symptoms||'暂无情况说明')} → {actionLabel(x.actions)}</p><div className="playbook-meta"><span>使用 {x.hit_count??'未知'} 次</span><span>{x.success_count==null?'成功次数待统计':`成功 ${x.success_count} 次`}</span><span>复用 {x.reuse_count??'未知'} 次</span><span>{x.publish_state==='local_only'||x.status?.publish_state==='local_only'?'已保存于本机':'当前状态未知'}</span></div></article>)}</div></main>}
createRoot(document.getElementById('root')!).render(<App />)
