import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Archive, ArrowClockwise, Brain, CheckCircle, CloudSlash, Command, Gauge, GitBranch, Lightning, Pause, Play, Plug, Pulse, Robot, ShieldCheck, SlidersHorizontal, Sparkle, TerminalWindow, UserCircle, Warning, X } from '@phosphor-icons/react'
import './styles.css'
import './overrides.css'
import './scene.css'
import './matrix.css'
import './sprite.css'
import './sprite-fix.css'
import OfficeScene from './OfficeScene'
import './playbook.css'
import './compact.css'

type Agent={id:string;role:string;name:string;status:string;heartbeat_at:string|null;task_id:string|null;detail:string;capabilities:string[]}
type Incident={id:string;run_id:string;status:string;opened_at:string;closed_at:string|null;symptoms:string[];scenario:string;plan:any;verification:any;elapsed_s:number|null}
type EventItem={event_id:string;sequence:number;event_type:string;occurred_at:string;run_id:string|null;incident_id:string|null;producer:string;generation:string;payload:Record<string,any>}
type State={generation:string;autonomy:'L0'|'L1'|'L2';muted:boolean;monitoring:boolean;memory_enabled:boolean;config:any;agents:Agent[];incident:Incident|null;runs:any[];metrics:any;dependencies:any;playbooks:any[];events:EventItem[];attract:{enabled:boolean;cycle:number;auto_running?:boolean;url?:string};model:string;version:string}
const emptyState:State={generation:'?',autonomy:'L2',muted:false,monitoring:false,memory_enabled:false,config:{revision:'?',prompt_version:'unknown',context_multiplier:1,max_output_tokens:256,retry_limit:3,retry_on_terminal:false},agents:[],incident:null,runs:[],metrics:{total:0,success:0,failures:0,usage_tokens:0},dependencies:{},playbooks:[],events:[],attract:{enabled:false,cycle:0},model:'unknown',version:'0.1.0'}
const api=async <T,>(path:string, init?:RequestInit):Promise<T>=>{const r=await fetch(path,{...init,headers:{'Content-Type':'application/json',...(init?.headers||{})}});let b:any={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b?.error?.message||b?.detail||`HTTP ${r.status}`);return b}
const post=(path:string,body:any={},options?:RequestInit)=>api<any>(path,{...options,method:'POST',body:JSON.stringify(body)})
const put=(path:string,body:any)=>api<any>(path,{method:'PUT',body:JSON.stringify(body)})
const clock=(v?:string|null)=>v?new Date(v).toLocaleTimeString('zh-CN',{hour12:false}):'—'
const safeText=(v:any):string=>{if(v===null||v===undefined)return '未知';if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')return String(v);if(Array.isArray(v))return v.map(safeText).join(' · ');try{return JSON.stringify(v)}catch{return '不可序列化'}}
function App(){
 const [state,setState]=useState<State>(emptyState),[offline,setOffline]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState<'office'|'runs'|'playbooks'|'score'>('office'),[chat,setChat]=useState(''),[messages,setMessages]=useState<{from:string;text:string;time:string}[]>([]),[busy,setBusy]=useState<string|null>(null),[liveEvents,setLiveEvents]=useState<EventItem[]>([])
 const chatEpoch=useRef(0),chatAbort=useRef<AbortController|null>(null)
 const eventSeq=useRef(0)
 const refresh=useCallback(async()=>{try{const s=await api<State>('/api/state');setState(s);setOffline(false);setError('')}catch(e){setOffline(true);setError((e as Error).message)}},[])
 useEffect(()=>{refresh();const timer=setInterval(refresh,12000);return()=>clearInterval(timer)},[refresh])
 const [sseStatus,setSseStatus]=useState<'connecting'|'open'|'reconnecting'>('connecting')
 useEffect(()=>{let es:EventSource|undefined;let timer:number|undefined;try{es=new EventSource('/api/events?after='+eventSeq.current);es.onopen=()=>setSseStatus('open');es.addEventListener('update',(ev)=>{const x=JSON.parse((ev as MessageEvent).data) as EventItem;eventSeq.current=x.sequence;setLiveEvents(v=>[x,...v].slice(0,30));window.clearTimeout(timer);timer=window.setTimeout(refresh,300)});es.onerror=()=>setSseStatus('reconnecting')}catch{setSseStatus('reconnecting')}return()=>{window.clearTimeout(timer);es?.close()}},[refresh])
 const act=async(key:string,fn:()=>Promise<any>)=>{setBusy(key);setError('');try{await fn();await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(null)}}
 const sendChat=async()=>{if(!chat.trim()||busy==='reset')return;const q=chat.trim();setChat('');const epoch=++chatEpoch.current;const controller=new AbortController();chatAbort.current=controller;setMessages(m=>[...m,{from:'operator',text:q,time:new Date().toISOString()}]);setBusy('chat');setError('');try{const r=await post('/api/chat',{message:q},{signal:controller.signal});if(epoch!==chatEpoch.current)return;if(r.status==='cancelled'){setMessages(m=>[...m,{from:'系统',text:'本轮已重置，请求已取消。',time:new Date().toISOString()}]);return}if(r.status==='error'||r.status==='timeout')throw new Error(`客服请求${r.status==='timeout'?'超时':'失败'}：未生成正常回答`);setMessages(m=>[...m,{from:'小智',text:r.answer||r.structured?.answer||'模型未返回可显示内容',time:new Date().toISOString()}]);}catch(e){if(epoch===chatEpoch.current&&(e as Error).name!=='AbortError')setError((e as Error).message)}finally{if(epoch===chatEpoch.current){chatAbort.current=null;setBusy(v=>v==='chat'?null:v)}}}
 const resetLab=async()=>{if(busy==='reset')return;chatEpoch.current++;chatAbort.current?.abort();chatAbort.current=null;setBusy('reset');setError('');try{await post('/api/reset',{});setMessages(m=>[...m,{from:'系统',text:'本轮已重置，请求已取消。',time:new Date().toISOString()}]);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(v=>v==='reset'?null:v)}}
 const inject=(scenario:string)=>{if(state.memory_enabled&&state.muted){setError('记忆复用与禁言不能同时注入，请先关闭其中一项。');return}return act('inject-'+scenario,()=>post('/api/inject',{scenario,condition:state.muted?'muted':state.memory_enabled?'memory':'swarm'}))}
 const officeEvents=[...new Map([...liveEvents,...(state.events||[])].map(e=>[String(e.sequence),e])).values()].sort((a,b)=>Number(b.sequence)-Number(a.sequence))
 const latest=officeEvents.slice(0,10)
 const fixer=state.agents.find(a=>a.id==='fixer-a'), specialist=state.agents.find(a=>a.id.includes('cost'))
 return <div className="app-shell">
   <header className="topbar"><div className="brand"><span className="brand-mark">S9</span><div><strong>SECTION 9</strong><small>客服代理实验室 / OPERATIONS FLOOR</small></div></div><div className="top-meta"><span className={offline?'offline':'online'}><i/> {offline?'离线 · 等待后端':'控制链路在线'}</span><span className="sse-state">SSE {sseStatus==='open'?'LIVE':sseStatus==='reconnecting'?'RECONNECTING':'CONNECTING'}</span><span>GEN {state.generation}</span><span>REV {state.config?.revision||'?'}</span><button className="icon-btn" title="刷新状态" onClick={refresh}><ArrowClockwise size={18}/></button></div></header>
   {error&&<div className="error-banner"><Warning size={18}/><span>{error}</span><button onClick={()=>setError('')}><X size={16}/></button></div>}
   <div className="toolbar"><div className="tabs"><button className={tab==='office'?'active':''} onClick={()=>setTab('office')}><Command/>办公室</button><button className={tab==='runs'?'active':''} onClick={()=>setTab('runs')}><Pulse/>运行记录</button><button className={tab==='playbooks'?'active':''} onClick={()=>setTab('playbooks')}><Archive/>Playbook</button><button className={tab==='score'?'active':''} onClick={()=>setTab('score')}><Gauge/>五行计分</button></div><div className="toolbar-right"><span className="model-chip"><Brain size={15}/> {state.model||'模型未知'}</span><button className="ghost" onClick={resetLab} disabled={busy==='reset'}><ArrowClockwise/>重置实验室</button></div></div>
   {tab==='office'?<main className="workspace">
      <section className="left-column"><div className="section-heading"><div><span className="eyebrow">LIVE CONTROL ROOM</span><h1>可观测协作现场</h1></div><div className="status-led"><span className="pulse"/>{state.monitoring?'MONITORING':'STANDBY'}</div></div>
       <div className="flow-chain"><div className="flow-step active"><b>01</b><strong>小智客服</strong><small>真实会话进入控制室</small></div><i>→</i><div className={'flow-step '+(state.incident?'active':'')}><b>02</b><strong>异常</strong><small>{state.incident?state.incident.symptoms?.join(' / '):'等待事件信号'}</small></div><i>→</i><div className={'flow-step '+(state.incident?.plan?'active':'')}><b>03</b><strong>协作</strong><small>{state.incident?.plan?'计划与代理动作':'待命'}</small></div><i>→</i><div className={'flow-step '+(state.incident?.verification?'active':'')}><b>04</b><strong>验收</strong><small>{state.incident?.verification?'独立检查结果':'未测'}</small></div></div>
       <div className="chat-dock"><div><span className="eyebrow">LIVE CUSTOMER CHANNEL</span><strong>小智客服</strong><small>真实模型请求 · 回复会进入证据链</small></div><input value={chat} onChange={e=>setChat(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendChat()} placeholder="输入售后问题，例如：X200 激活后还能退吗？" aria-label="客服消息"/><button onClick={sendChat} disabled={busy==='chat'||!chat.trim()}>{busy==='chat'?'请求中':'发送消息'}</button></div>
       <OfficeScene agents={state.agents} events={officeEvents} generation={state.generation} incidentStatus={state.incident?.status||null} activeRunId={state.incident?.run_id||state.incident?.id||null} muted={state.muted} connected={!offline}/>
       <div className="inject-strip"><div><span className="eyebrow">CHAOS INJECTOR</span><p>触发真实运行；事件会从 SSE 回到此处。</p></div><div className="inject-buttons"><button onClick={()=>inject('prompt')} disabled={!!busy}><Warning/>语义退化</button><button onClick={()=>inject('cost')} disabled={!!busy}><Lightning/>成本膨胀</button><button onClick={()=>inject('loop')} disabled={!!busy}><ArrowClockwise/>工具死循环</button><button onClick={()=>inject('composite')} disabled={!!busy}><GitBranch/>复合故障</button></div></div>
      <div className="lower-grid"><Panel title="客服窗口" icon={<UserCircle/>}><div className="chat-log">{messages.length===0&&<div className="empty">尚无本次会话。发送一条真实问题开始。</div>}{messages.map((m,i)=><div className={'msg '+m.from} key={i}><span>{m.from==='operator'?'OPERATOR':'小智'} · {clock(m.time)}</span><p>{m.text}</p></div>)}</div><div className="chat-input"><input value={chat} onChange={e=>setChat(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendChat()} placeholder="问一个售后问题…" aria-label="客服消息"/><button onClick={sendChat} disabled={busy==='chat'||!chat.trim()}>{busy==='chat'?'…':'发送'}</button></div></Panel><Panel title="事件时间线" icon={<Pulse/>}><div className="event-feed">{latest.length===0&&<div className="empty">等待事件流…</div>}{latest.map(e=><div className="event-row" key={e.sequence}><span className="event-seq">{String(e.sequence).padStart(3,'0')}</span><div><strong>{e.event_type}</strong><small>{e.payload?.summary||e.payload?.message||e.payload?.reason||'无摘要'}</small></div><time>{clock(e.occurred_at)}</time></div>)}</div></Panel></div>
      </section>
      <aside className="right-column"><Panel title="控制台" icon={<SlidersHorizontal/>}><div className="control-line"><span>自主等级</span><div className="segmented">{(['L0','L1','L2'] as const).map(l=><button key={l} className={state.autonomy===l?'selected':''} onClick={()=>act(l,()=>put('/api/autonomy',{level:l}))}>{l}</button>)}</div></div><div className="control-line"><span>消息层</span><button className={'toggle '+(state.muted?'on':'')} onClick={()=>act('mute',()=>put('/api/communication',{muted:!state.muted}))}><i/>{state.muted?'已禁言':'正常通信'}</button></div><div className="control-line"><span>下轮 Playbook</span><button className={'toggle '+(state.memory_enabled?'on':'')} onClick={()=>act('memory',async()=>{const r=await put('/api/memory',{enabled:!state.memory_enabled});if(typeof r.enabled==='boolean')setState(s=>({...s,memory_enabled:r.enabled}))})}><i/>{state.memory_enabled?'记忆复用':'关闭'}</button></div><div className="control-line"><span>Attract 循环</span><button className={'toggle '+(state.attract?.enabled?'on':'')} onClick={()=>act('attract',()=>put('/api/attract',{enabled:!state.attract?.enabled}))}><i/>{state.attract?.enabled?(state.attract.auto_running===false&&state.attract.cycle>=3?'导览完成':'运行中'):'关闭'}</button></div>{state.attract?.enabled&&<a className="attract-link" href={state.attract.url||'http://127.0.0.1:9020'} target="_blank" rel="noreferrer">独立实验进程 · 9020 · 最多 3 轮</a>}<div className="control-line"><span>模型推理</span><span className={'value dep-'+(state.dependencies?.model?.status||'unknown')}>{state.dependencies?.model?.status||'unknown'} · {state.dependencies?.model?.detail||'状态未知'}</span></div></Panel>
      <Panel title="代理状态" icon={<Robot/>}><div className="agents">{state.agents.map(a=><div className="agent" key={a.id}><span className={'agent-dot '+a.status}/><div><strong>{a.name}<em>{a.role}</em></strong><small>{a.detail||'—'} · {clock(a.heartbeat_at)}</small></div><span className="agent-state">{a.status}</span></div>)}{state.agents.length===0&&<div className="empty">状态快照尚未返回代理。</div>}</div><div className="agent-actions"><button onClick={()=>act('join',()=>post('/api/agents/join'))}><Sparkle/>成本专家加入</button>{fixer&&<><button onClick={()=>act('pause',()=>post('/api/agents/fixer-a/pause'))} disabled={fixer.status==='paused'}><Pause/>暂停 A</button><button onClick={()=>act('resume',()=>post('/api/agents/fixer-a/resume'))} disabled={fixer.status!=='paused'}><Play/>恢复 A</button></>}</div></Panel>
      <Panel title="当前异常" icon={<ShieldCheck/>}><IncidentCard incident={state.incident} busy={busy} onApprove={()=>act('approve',()=>post('/api/approve',{plan_id:state.incident?.plan?.id||''}))} onFencing={()=>act('fencing',()=>post('/api/demo/fencing'))}/></Panel>
      <Panel title="依赖健康" icon={<Plug/>}><div className="deps">{Object.entries(state.dependencies||{}).map(([k,v]:any)=><div key={k}><span className={'dep-dot '+v.status}/><span>{k==='langfuse'&&v.url?<a href={v.url} target="_blank" rel="noreferrer">{k}</a>:k}</span><small>{v.detail||v.status||'unknown'}</small></div>)}</div></Panel>
      </aside>
   </main>:tab==='playbooks'?<PlaybookView/>:<DataView tab={tab} state={state} refresh={refresh}/>}<footer><span><TerminalWindow/> SECTION 9 / LOCAL OPERATOR CONSOLE</span><span>状态来源：GET /api/state + SSE /api/events · 未测状态不会生成分数</span></footer>
 </div>
}
function Panel({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="panel"><div className="panel-title"><span>{icon}</span><strong>{title}</strong><i/></div>{children}</section>}
function IncidentCard({incident,busy,onApprove,onFencing}:{incident:Incident|null;busy:string|null;onApprove:()=>void;onFencing:()=>void}){if(!incident)return <div className="empty incident-empty"><CheckCircle size={24}/>当前没有活动异常<div className="empty-sub">可从左侧注入器开始一次真实运行。</div><button onClick={onFencing} disabled={!!busy}><GitBranch/>演示 fencing 剧本</button></div>;const approvable=incident.plan?.status==='proposed'||incident.plan?.status==='pending';return <div className="incident-card"><div className="incident-head"><span className="severity">{incident.status}</span><code>{incident.id}</code></div><h3>{incident.scenario||'未命名场景'}</h3><p>{incident.symptoms?.join(' / ')||'症状待事件流补充'}</p><div className="incident-meta"><span>OPENED {clock(incident.opened_at)}</span><span>ELAPSED {incident.elapsed_s??'—'}s</span></div>{incident.plan&&<div className="plan"><span>PLAN {incident.plan.status}</span><small>{incident.plan.id}</small><p className="plan-rationale">{incident.plan.rationale||'暂无 rationale'}</p><pre>{safeText(incident.plan.actions||[])}</pre><button onClick={onApprove} disabled={busy==='approve'||!approvable}>{approvable?'批准计划':incident.plan.status==='approved'?'已批准':'已处理'}</button></div>}</div>}
function DataView({tab,state,refresh}:{tab:string;state:State;refresh:()=>void}){
 const [data,setData]=useState<any>(null),[err,setErr]=useState(''),[detail,setDetail]=useState<any>(null),[detailKind,setDetailKind]=useState(''),[selectedVersion,setSelectedVersion]=useState('')
 const dataSeq=useRef(0)
 const stateKey=useMemo(()=>JSON.stringify({generation:state.generation,muted:state.muted,memory_enabled:state.memory_enabled,incident:state.incident&&{id:state.incident.id,status:state.incident.status,run_id:state.incident.run_id},metrics:state.metrics,agents:state.agents.map(a=>[a.id,a.status,a.task_id])}),[state])
 useEffect(()=>{let alive=true;let timer:number|undefined;const controller=new AbortController();const base=tab==='runs'?'/api/runs':tab==='playbooks'?'/api/playbooks':'/api/scoreboard';const p=tab==='score'&&selectedVersion?`${base}?version=${encodeURIComponent(selectedVersion)}`:base;const load=async()=>{const seq=++dataSeq.current;try{const d=await api<any>(p,{signal:controller.signal});if(alive&&seq===dataSeq.current)setData(d)}catch(e){if(alive&&(e as Error).name!=='AbortError')setErr((e as Error).message)}};setData(null);setErr('');load();timer=window.setInterval(load,3000);return()=>{alive=false;controller.abort();window.clearInterval(timer)}},[tab,stateKey,selectedVersion])
 const openDetail=async(id:string,kind:string)=>{setDetailKind(kind);setDetail(null);try{if(kind==='run'){const [run,rca]=await Promise.all([api<any>(`/api/runs/${id}`),api<any>(`/api/rca/${id}`)]);setDetail({...run,...rca,events:run.events||[],evidence:rca.evidence||[],verification:run.verification||rca.verification})}else setDetail(await api<any>(`/api/rca/${id}`))}catch(e){setDetail({error:(e as Error).message})}}
 if(err)return <main className="data-view"><div className="empty"><CloudSlash size={30}/>{err}<button onClick={refresh}>重试</button></div></main>
 if(!data)return <main className="data-view"><div className="loading"><span/>正在读取真实数据…</div></main>
 const effectiveVersion=selectedVersion||data.selected_version||data.current_version||''
 return <main className="data-view"><div className="data-heading"><div><span className="eyebrow">{tab==='runs'?'RUN RECORDS':tab==='playbooks'?'REUSABLE PLAYBOOKS':'EVALUATION SCOREBOARD'}</span><h1>{tab==='runs'?'运行记录':tab==='playbooks'?'Playbook 库':'五行计分屏'}</h1></div><span className="data-note">动态数据 / {new Date().toLocaleTimeString('zh-CN',{hour12:false})}</span></div>{tab==='score'?<ScoreMatrix data={data} openDetail={openDetail} selectedVersion={effectiveVersion} onVersionChange={setSelectedVersion}/>:<div className="data-list">{(data.items||[]).length===0&&<div className="empty">暂无记录。只有真实 API 返回后才会出现条目。</div>}{(data.items||[]).map((x:any,i:number)=><article key={x.id||i} onClick={()=>tab==='runs'&&x.id&&openDetail(x.id,'run')}><div className="list-id">{x.id||'—'}</div><div><h3>{x.title||x.scenario||x.status||'记录'}</h3><p>{x.summary||x.symptoms?.join(' / ')||x.source||'暂无摘要'}</p></div><time>{clock(x.opened_at||x.created_at)}</time>{tab==='runs'&&<button className="detail-button">查看详情 / RCA</button>}</article>)}</div>}{detail&&<DetailDrawer detail={detail} kind={detailKind} onClose={()=>setDetail(null)}/>}</main>
}
function ScoreMatrix({data,openDetail,selectedVersion,onVersionChange}:{data:any;openDetail:(id:string,kind:string)=>void;selectedVersion:string;onVersionChange:(version:string)=>void}){const rows=data.rows||[];const scenarios=['prompt','cost','loop','composite'];const [selected,setSelected]=useState<string[]|null>(null);const versions=Array.isArray(data.versions)?data.versions:[];return <><div className="score-controls"><label htmlFor="score-version">验收版本</label><select id="score-version" value={selectedVersion} onChange={e=>{setSelected(null);onVersionChange(e.target.value)}}>{versions.length===0&&<option value={selectedVersion}>{selectedVersion||'当前版本'}</option>}{versions.map((v:any)=><option key={v.id} value={v.id}>{v.label||v.id} · N {v.n??0}</option>)}</select>{data.limitations&&<small>{safeText(data.limitations)}</small>}</div><div className="score-matrix"><div className="matrix-head"><span>条件</span>{scenarios.map(s=><span key={s}>{s}</span>)}</div>{rows.map((r:any)=><div className="matrix-row" key={r.id}><strong>{r.label}</strong>{scenarios.map(s=>{const c=(r.cells||[]).find((x:any)=>x.scenario===s);const ids=c?.run_ids||[];return <button className="matrix-cell" key={s} disabled={!ids.length} onClick={()=>setSelected(ids)}><b>{c?.n===0||!c?.n?'待测':`N ${c.n}`}</b><small>{c?.n?`失败 ${c.failures??'未知'} · ${c.median_s==null?'未知':c.median_s+'s'}`:'未知失败 · 未知耗时'}</small><small>{c?.n?(c.usage_tokens==null?'已知token小计未知':`已知token小计 ${c.usage_tokens}`):'budget 未测'}</small>{c?.n&&c?.unknown_usage_runs>0&&<small>未知usage {c.unknown_usage_runs}轮</small>}</button>})}</div>)}</div>{selected&&<div className="run-picker"><div className="run-picker-head"><strong>选择逐次记录</strong><button onClick={()=>setSelected(null)}>关闭</button></div>{selected.map(id=><button key={id} onClick={()=>openDetail(id,'run')}>{id}</button>)}</div>}</>}
function DetailDrawer({detail,kind,onClose}:{detail:any;kind:string;onClose:()=>void}){const [loading,setLoading]=useState(!detail);if(loading)return <div className="detail-drawer"><div className="drawer-head"><strong>读取详情</strong><button onClick={onClose}>关闭</button></div><div className="loading"><span/>读取真实证据…</div></div>;const summary=typeof detail.summary==='string'?detail.summary:safeText(detail.summary);const events=Array.isArray(detail.events)?detail.events:[];const evidence=Array.isArray(detail.evidence)?detail.evidence:[];const displayEvents=events.length?events:[...new Map(evidence.map((x:any)=>[x.event_id||JSON.stringify(x),x])).values()];const checks=Array.isArray(detail.checks)?detail.checks:(Array.isArray(detail.verification?.checks)?detail.verification.checks:[]);const actions=Array.isArray(detail.actions)?detail.actions:(Array.isArray(detail.plan?.actions)?detail.plan.actions:[]);return <div className="detail-drawer"><div className="drawer-head"><strong>{kind==='rca'?'RCA / 运行证据':'运行详情'}</strong><button onClick={onClose}>关闭</button></div>{detail.error?<div className="empty"><CloudSlash size={25}/>{safeText(detail.error)}</div>:<div className="drawer-body"><div className="detail-title">{safeText(detail.title||summary||detail.run_id||'详情')}</div><div className="detail-kv"><span>STATUS</span>{safeText(detail.status)}</div><div className="detail-kv"><span>USAGE</span>{safeText(detail.usage||detail.usage_tokens||'未知 / 未测')}</div>{summary&&<p className="detail-summary">{summary}</p>}<h4>verification checks</h4>{checks.length?checks.map((x:any,i:number)=><div className={'detail-check '+(x.passed?'passed':'failed')} key={i}><strong>{x.passed?'PASS':'FAIL'} · {safeText(x.name)}</strong><small>expected: {safeText(x.expected)} · actual: {safeText(x.actual)}</small></div>):<div className="detail-muted">无 checks 记录</div>}<h4>evidence events</h4>{displayEvents.map((x:any,i:number)=><div className="detail-event" key={x.event_id||i}><code>{safeText(x.event_type||'evidence')}</code><span>{safeText(x.producer||'unknown')} · {clock(x.occurred_at)} · {safeText(x.event_id||'—')}</span><p>{safeText(x.payload?.summary||x.payload?.message||x.summary||x)}</p></div>)}<h4>plan actions</h4><pre>{safeText(actions)}</pre></div>}</div>}
function PlaybookView(){const [data,setData]=useState<any>(null),[error,setError]=useState('');useEffect(()=>{api<any>('/api/playbooks').then(setData).catch(e=>setError(e.message))},[]);if(error)return <main className="data-view"><div className="empty">{error}</div></main>;if(!data)return <main className="data-view"><div className="loading"><span/>正在读取真实 Playbook…</div></main>;return <main className="data-view"><div className="data-heading"><div><span className="eyebrow">REUSABLE PLAYBOOKS</span><h1>Playbook 库</h1></div></div><div className="playbook-list">{(data.items||[]).length===0&&<div className="empty">暂无 Playbook；真实运行成功后才会出现。</div>}{(data.items||[]).map((x:any,i:number)=><article className="playbook-card" key={x.id||i}><div className="playbook-top"><span>{x.publish_state||x.status?.publish_state||'unknown'}</span><code>{x.id||'—'}</code></div><h3>{x.title||'未命名 Playbook'}</h3><p>{safeText(x.symptoms||'暂无症状')} → {safeText(x.actions||'暂无动作')}</p><div className="playbook-meta"><span>命中 {x.hit_count??'未知'}</span><span>验证成功 {x.success_count??'未知'}</span><span>复用 {x.reuse_count??'未知'}</span><span>{x.source||'来源未知'}</span><span>{x.publish_state==='local_only'||x.status?.publish_state==='local_only'?'本地已保存 · Hub 未发布':x.publish_state==='pending_auth'||x.status?.hub_status==='pending_auth'?'本地未发布 · Hub 发布器未实现':'发布状态未知'}</span></div></article>)}</div></main>}
createRoot(document.getElementById('root')!).render(<App />)
